version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - HOST=0.0.0.0
      - DEBUG=true
    volumes:
      - ./api:/app
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 8000

  web:
    build: ./web
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
      - VITE_WS_URL=ws://localhost:8000/ws
    volumes:
      - ./web:/app
      - /app/node_modules
    depends_on:
      - api
    command: yarn dev --host